# Generated by Django 5.2.6 on 2025-11-13 17:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_builder', '0002_warehousezone_width_warehousezone_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserack',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('20.00'))], verbose_name='Wysokość'),
        ),
        migrations.AddField(
            model_name='warehouserack',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('20.00'))], verbose_name='Szerokość'),
        ),
        migrations.AddField(
            model_name='warehouseshelf',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))], verbose_name='Wysokość'),
        ),
        migrations.AddField(
            model_name='warehouseshelf',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('15.00'))], verbose_name='Szerokość'),
        ),
    ]
