# Generated by Django 5.2.6 on 2025-11-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_alter_pickingitem_location'),
        ('wms_builder', '0003_warehouserack_height_warehouserack_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserack',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_rack', to='wms.location', verbose_name='Lokalizacja WMS'),
        ),
        migrations.AddField(
            model_name='warehouseshelf',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_shelf', to='wms.location', verbose_name='Lokalizacja WMS'),
        ),
        migrations.AddField(
            model_name='warehousezone',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_zone', to='wms.location', verbose_name='Lokalizacja WMS'),
        ),
    ]
