# Generated by Django 5.2.6 on 2025-11-14 16:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_builder', '0004_warehouserack_location_warehouseshelf_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouserack',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Wysokość'),
        ),
        migrations.AlterField(
            model_name='warehouserack',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Szerokość'),
        ),
        migrations.AlterField(
            model_name='warehouseshelf',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Wysokość'),
        ),
        migrations.AlterField(
            model_name='warehouseshelf',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Szerokość'),
        ),
        migrations.AlterField(
            model_name='warehousezone',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Wysokość'),
        ),
        migrations.AlterField(
            model_name='warehousezone',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Szerokość'),
        ),
    ]
