# Generated by Django 5.2.6 on 2025-11-15 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfettiGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('value_type', models.CharField(blank=True, help_text='Optional hint for clients about the expected JSON type.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Confetti global setting',
                'verbose_name_plural': 'Confetti global settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ConfettiUserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confetti_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confetti user setting',
                'verbose_name_plural': 'Confetti user settings',
                'ordering': ['user_id', 'key'],
                'indexes': [models.Index(fields=['key'], name='confetti_co_key_231f8b_idx'), models.Index(fields=['user', 'key'], name='confetti_co_user_id_82ff74_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
