# Generated by Django 5.2.6 on 2025-10-20 14:48

import assets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nazwa')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Kolor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.category', verbose_name='Kategoria nadrzędna')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('file', models.FileField(upload_to=assets.models.asset_upload_path, verbose_name='Plik')),
                ('file_type', models.CharField(choices=[('image', 'Obraz'), ('pdf', 'PDF'), ('document', 'Dokument'), ('video', 'Wideo'), ('audio', 'Audio'), ('other', 'Inne')], max_length=20, verbose_name='Typ pliku')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('is_public', models.BooleanField(default=True, verbose_name='Publiczne')),
                ('is_splash_image', models.BooleanField(default=False, verbose_name='Obraz splash')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dodane przez')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.category', verbose_name='Kategoria')),
                ('tags', models.ManyToManyField(blank=True, to='assets.tag', verbose_name='Tagi')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assety',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
