# Generated by Django 5.2.4 on 2025-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
