# Generated by Django 5.2.4 on 2025-07-23 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numer zamówienia')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nazwa klienta')),
                ('customer_address', models.TextField(verbose_name='Adres dostawy')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data zamówienia')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('in_progress', 'W kompletacji'), ('completed', 'Zrealizowane'), ('partially_completed', 'Częściowo zrealizowane'), ('cancelled', 'Anulowane')], default='pending', max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Wartość całkowita')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zamówienie klienta',
                'verbose_name_plural': 'Zamówienia klientów',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod produktu')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa produktu')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Kod kreskowy')),
                ('unit', models.CharField(default='szt', max_length=20, verbose_name='Jednostka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod lokalizacji')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa lokalizacji')),
                ('location_type', models.CharField(choices=[('shelf', 'Półka'), ('rack', 'Regał'), ('zone', 'Strefa')], default='shelf', max_length=20)),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Kod kreskowy lokalizacji')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.location', verbose_name='Lokalizacja nadrzędna')),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ilość zamówiona')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena jednostkowa')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena całkowita')),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ilość zrealizowana')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.customerorder', verbose_name='Zamówienie')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Pozycja zamówienia',
                'verbose_name_plural': 'Pozycje zamówienia',
            },
        ),
        migrations.CreateModel(
            name='PickingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numer zlecenia')),
                ('status', models.CharField(choices=[('created', 'Utworzone'), ('in_progress', 'W trakcie'), ('completed', 'Zakończone'), ('cancelled', 'Anulowane')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Rozpoczęto')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zakończono')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Przypisane do')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.customerorder', verbose_name='Zamówienie klienta')),
            ],
            options={
                'verbose_name': 'Zlecenie kompletacji',
                'verbose_name_plural': 'Zlecenia kompletacji',
            },
        ),
        migrations.CreateModel(
            name='PickingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_pick', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ilość do pobrania')),
                ('quantity_picked', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ilość pobrana')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Zakończone')),
                ('sequence', models.IntegerField(default=0, verbose_name='Kolejność')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.location', verbose_name='Lokalizacja')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.orderitem', verbose_name='Pozycja zamówienia')),
                ('picking_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.pickingorder', verbose_name='Zlecenie kompletacji')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Pozycja kompletacji',
                'verbose_name_plural': 'Pozycje kompletacji',
            },
        ),
        migrations.CreateModel(
            name='PickingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_picked', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ilość pobrana')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='Czas skanowania')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('location_scanned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.location', verbose_name='Zeskanowana lokalizacja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('picking_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.pickingitem', verbose_name='Pozycja kompletacji')),
                ('product_scanned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Zeskanowany produkt')),
            ],
            options={
                'verbose_name': 'Historia kompletacji',
                'verbose_name_plural': 'Historia kompletacji',
            },
        ),
        migrations.CreateModel(
            name='WarehouseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Numer dokumentu')),
                ('document_type', models.CharField(choices=[('wz', 'Wydanie Zewnętrzne'), ('pz', 'Przyjęcie Zewnętrzne')], default='wz', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Wartość całkowita')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.customerorder', verbose_name='Zamówienie klienta')),
                ('picking_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.pickingorder', verbose_name='Zlecenie kompletacji')),
            ],
            options={
                'verbose_name': 'Dokument magazynowy',
                'verbose_name_plural': 'Dokumenty magazynowe',
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ilość')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena jednostkowa')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena całkowita')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.location', verbose_name='Lokalizacja')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Produkt')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.warehousedocument', verbose_name='Dokument')),
            ],
            options={
                'verbose_name': 'Pozycja dokumentu',
                'verbose_name_plural': 'Pozycje dokumentu',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ilość')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ilość zarezerwowana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.location', verbose_name='Lokalizacja')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Stan magazynowy',
                'verbose_name_plural': 'Stany magazynowe',
                'unique_together': {('product', 'location')},
            },
        ),
    ]
