# Generated by Django 5.2.6 on 2025-11-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gt_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID użytkownika GT'),
        ),
    ]
