# Generated by Django 5.2.4 on 2025-07-24 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_code', models.CharField(blank=True, max_length=50)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('confirmed', 'Potwierdzone'), ('in_transit', 'W transporcie'), ('received', 'Przyjęte'), ('partially_received', 'Częściowo przyjęte'), ('cancelled', 'Anulowane')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='documentitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehousedocument',
            options={'ordering': ['-document_date']},
        ),
        migrations.AlterUniqueTogether(
            name='documentitem',
            unique_together={('document', 'product', 'location')},
        ),
        migrations.RemoveField(
            model_name='warehousedocument',
            name='picking_order',
        ),
        migrations.RemoveField(
            model_name='warehousedocument',
            name='total_value',
        ),
        migrations.AddField(
            model_name='warehousedocument',
            name='document_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='warehousedocument',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.warehousedocument'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.location'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='warehousedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='warehousedocument',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.customerorder'),
        ),
        migrations.AlterField(
            model_name='warehousedocument',
            name='document_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='warehousedocument',
            name='document_type',
            field=models.CharField(choices=[('PZ', 'Przyjęcie zewnętrzne'), ('WZ', 'Wydanie zewnętrzne'), ('MM', 'Przesunięcie międzymagazynowe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='warehousedocument',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ReceivingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('in_progress', 'W trakcie'), ('completed', 'Zakończone'), ('cancelled', 'Anulowane')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_orders', to='wms.supplierorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receiving_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wms.receivingorder')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddField(
            model_name='warehousedocument',
            name='supplier_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.supplierorder'),
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product')),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.supplierorder')),
            ],
            options={
                'unique_together': {('supplier_order', 'product')},
            },
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='total_price',
        ),
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product')),
                ('receiving_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.receivingorder')),
                ('supplier_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.supplierorderitem')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('receiving_order', 'supplier_order_item')},
            },
        ),
    ]
