# Generated by Django 5.2.4 on 2025-07-24 11:59

import django.db.models.deletion
import wms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_supplierorder_alter_documentitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=wms.models.user_avatar_path, verbose_name='Avatar')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Dział')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Stanowisko')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Profil użytkownika',
                'verbose_name_plural': 'Profile użytkowników',
            },
        ),
    ]
