# Generated by Django 5.2.6 on 2025-11-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_userprofile_gt_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa firmy')),
                ('short_name', models.CharField(blank=True, max_length=120, verbose_name='Skrócona nazwa')),
                ('tax_id', models.CharField(blank=True, max_length=32, verbose_name='NIP / Tax ID')),
                ('vat_id', models.CharField(blank=True, max_length=32, verbose_name='VAT ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adres e-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Strona www')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmy',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekujące'), ('created', 'Utworzona kompletacja'), ('in_progress', 'W kompletacji'), ('completed', 'Zrealizowane'), ('partially_completed', 'Częściowo zrealizowane'), ('cancelled', 'Anulowane')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekujące'), ('confirmed', 'Potwierdzone'), ('in_transit', 'W transporcie'), ('in_receiving', 'W regalacji'), ('received', 'Przyjęte'), ('partially_received', 'Częściowo przyjęte'), ('cancelled', 'Anulowane')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('headquarters', 'Siedziba'), ('billing', 'Fakturowanie'), ('shipping', 'Wysyłka'), ('warehouse', 'Magazyn'), ('office', 'Biuro'), ('other', 'Inny')], default='other', max_length=32, verbose_name='Typ adresu')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Opis adresu')),
                ('street', models.CharField(max_length=255, verbose_name='Ulica i numer')),
                ('street_extra', models.CharField(blank=True, max_length=255, verbose_name='Dodatkowe informacje')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=120, verbose_name='Miasto')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='Region / województwo')),
                ('country', models.CharField(default='Polska', max_length=120, verbose_name='Kraj')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Adres domyślny')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='wms.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Adres firmy',
                'verbose_name_plural': 'Adresy firmy',
                'ordering': ['company', '-is_primary', 'address_type', 'city'],
            },
        ),
    ]
