# Generated by Django 5.2.6 on 2025-11-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_company_alter_customerorder_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='companyaddress',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='companyaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='companyaddress',
            name='street_extra',
        ),
    ]
