# Generated by Django 5.2.4 on 2025-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia synchronizacja'),
        ),
        migrations.AddField(
            model_name='product',
            name='subiekt_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID w Subiekcie'),
        ),
        migrations.AddField(
            model_name='product',
            name='subiekt_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stan w Subiekcie'),
        ),
        migrations.AddField(
            model_name='product',
            name='subiekt_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena w Subiekcie'),
        ),
    ]
