# Generated by Django 5.2.6 on 2025-11-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_remove_company_tax_id_remove_companyaddress_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddress',
            name='name',
        ),
    ]
