# Generated by Django 5.2.4 on 2025-07-24 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_product_last_sync_date_product_subiekt_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa grupy')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod grupy')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Kolor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Grupa produktów',
                'verbose_name_plural': 'Grupy produktów',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='wms.productgroup', verbose_name='Grupa produktów'),
        ),
    ]
