# Generated by Django 5.2.6 on 2025-11-11 11:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_remove_companyaddress_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ilość')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Notatka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Wykonał')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Produkt')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_out', to='wms.location', verbose_name='Lokalizacja źródłowa')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_in', to='wms.location', verbose_name='Lokalizacja docelowa')),
            ],
            options={
                'verbose_name': 'Przesunięcie magazynowe',
                'verbose_name_plural': 'Przesunięcia magazynowe',
                'ordering': ['-created_at'],
            },
        ),
    ]
