# Generated by Django 5.2.4 on 2025-07-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_productgroup_product_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.AddField(
            model_name='product',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='products', to='wms.productgroup', verbose_name='Grupy produktów'),
        ),
    ]
