# Generated by Django 5.0.14 on 2025-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_remove_product_group_product_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subiekt_stock_reserved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stan zarezerwowany w Subiekcie'),
        ),
    ]
