# Generated by Django 5.2.6 on 2025-11-11 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('transfer', 'Przesunięcie'), ('inbound', 'Przyjęcie'), ('outbound', 'Wydanie')], default='transfer', max_length=10, verbose_name='Typ ruchu'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='wms.location', verbose_name='Lokalizacja źródłowa'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='wms.location', verbose_name='Lokalizacja docelowa'),
        ),
    ]
