# Generated by Django 5.0.14 on 2025-08-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_product_subiekt_stock_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subiekt_unit_price',
        ),
    ]
