# Generated by Django 5.2.6 on 2025-11-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_stockmovement_movement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Domyślna lokalizacja'),
        ),
    ]
