# Generated by Django 5.0.14 on 2025-08-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_remove_subiekt_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subiekt_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID w Subiekcie/PLU'),
        ),
    ]
