# Generated by Django 5.2.6 on 2025-11-11 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_location_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.location', verbose_name='Lokalizacja'),
        ),
    ]
